### ISSUE TITLE
Table 'surface.scanners_rootbox' doesn't exist

### ISSUE THREAD

**Issue by scrissti** [surface-security/surface#26]
I've installed the docker version as detailed in the README.
I get the following errors:
dev-resync-rootbox-1 | django.db.utils.ProgrammingError: (1146, "Table 'surface.scanners_rootbox' doesn't exist")

Please advise.

Full Trace
dev-resync-rootbox-1 | Traceback (most recent call last):
dev-resync-rootbox-1 | File "/surface/surface/./manage.py", line 22, in
dev-resync-rootbox-1 | main()
dev-resync-rootbox-1 | File "/surface/surface/./manage.py", line 18, in main
dev-resync-rootbox-1 | execute_from_command_line(sys.argv)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/core/management/init.py", line 419, in execute_from_command_line
dev-resync-rootbox-1 | utility.execute()
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/core/management/init.py", line 413, in execute
dev-resync-rootbox-1 | self.fetch_command(subcommand).run_from_argv(self.argv)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
dev-resync-rootbox-1 | self.execute(*args, **cmd_options)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/logbasecommand/base.py", line 64, in execute
dev-resync-rootbox-1 | super().execute(*args, **options)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
dev-resync-rootbox-1 | output = self.handle(*args, **options)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/database_locks/locks.py", line 126, in new_handle
dev-resync-rootbox-1 | return orig_handle(self, *args, **kwargs)
dev-resync-rootbox-1 | File "/surface/surface/scanners/management/commands/resync_rootbox.py", line 181, in handle
dev-resync-rootbox-1 | for rootbox in rootboxes:
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in iter
dev-resync-rootbox-1 | self._fetch_all()
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
dev-resync-rootbox-1 | self._result_cache = list(self._iterable_class(self))
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in iter
dev-resync-rootbox-1 | results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
dev-resync-rootbox-1 | cursor.execute(sql, params)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
dev-resync-rootbox-1 | return super().execute(sql, params)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
dev-resync-rootbox-1 | return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
dev-resync-rootbox-1 | return executor(sql, params, many, context)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
dev-resync-rootbox-1 | return self.cursor.execute(sql, params)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in exit
dev-resync-rootbox-1 | raise dj_exc_value.with_traceback(traceback) from exc_value
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
dev-resync-rootbox-1 | return self.cursor.execute(sql, params)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 73, in execute
dev-resync-rootbox-1 | return self.cursor.execute(query, args)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
dev-resync-rootbox-1 | res = self._query(query)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
dev-resync-rootbox-1 | db.query(q)
dev-resync-rootbox-1 | File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
dev-resync-rootbox-1 | _mysql.connection.query(self, query)
dev-resync-rootbox-1 | django.db.utils.ProgrammingError: (1146, "Table 'surface.scanners_rootbox' doesn't exist")

**Comment by gsilvapt** [comment]
Hi @scrissti ,

Thanks for reaching out! Did you run any additional commands other than the ones specified in the `README`?

**Comment by cristian-serban-tvp** [comment]
Hi Gustavo, 
I've created a fresh new Ubuntu machine and installed docker according to guide https://docs.docker.com/engine/install/ubuntu/
then I run the following commands:

```
git clone https://github.com/surface-security/surface/
cd surface
touch surface/local.env
sudo docker compose -f dev/docker-compose-in-a-box.yml up
```

Thanks for looking into this

Cristian

**Comment by gsilvapt** [comment]
> Hi Gustavo, I've created a fresh new Ubuntu machine and installed docker according to guide https://docs.docker.com/engine/install/ubuntu/ then I run the following commands:
> 
> ```
> git clone https://github.com/surface-security/surface/
> cd surface
> touch surface/local.env
> sudo docker compose -f dev/docker-compose-in-a-box.yml up
> ```
> 
> Thanks for looking into this
> 
> Cristian

Just spun a copy of Surface locally, and it worked. I followed the README and ran `dev/box_setup.sh` after the docker compose command. This runs Django's migrations and it's therefore vital to make that error go away.

**However** the Django server crashed because, when it was spinning, it could not connect to the MySQL database. This might have happened to you too, so you will have a 502 Gateway Error. List your running containers with `docker container ls -a` and restart the django server (should be named after something like `dev_surface`) with `docker container restart <id>`.

This should be enough to fix this issue at least.

Please let us know if you encounter any other issue - Otherwise, please close this issue.

**Comment by scrissti** [comment]
I execute dev/box_setup.sh and I get the following error message.

`dev/box_setup.sh: 7: Syntax error: "(" unexpected
`

**Comment by gsilvapt** [comment]
Did you make it executable first?

**Comment by scrissti** [comment]
it worked with "sudo bash box_setup.sh"
But when I try to access it from browser I get following error:
![image](https://user-images.githubusercontent.com/397224/188480292-6396c006-30fd-4bd7-a27c-882186fb4ff4.png)

**Comment by scrissti** [comment]
> Did you make it executable first?

yes, but same error. It worked in the end with sudo bash box_setup.sh

**Comment by scrissti** [comment]
works fine now. clossing the issue. Thank you

**Comment by gsilvapt** [comment]
Thanks for updating this one. Thanks a lot and hope it works flawless now :crossed_fingers:
